stages:          # List of stages for jobs, and their order of execution
  - test
  - build
  - deploy

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  image: gradle:jdk16
  tags:
    - docker
  script:
    - gradle check --info

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - shell 
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: always
  before_script:
    - "docker --version"
    - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
  script:
    - "docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_SHA} --pull ."
    - "docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_SHA}"
    - "docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest"
  after_script:
    - "docker logout ${CI_REGISTRY}"


deploy-job:
  stage: deploy
  tags:
    - shell
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: always
  before_script:
    - "docker --version"
    - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - "docker stack services IcelandicDiscordBot"
  script:
    - "docker pull  ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest"
    - "docker service update --with-registry-auth --image ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_SHA} IcelandicDiscordBot_bot"
  after_script:
    - "docker logout ${CI_REGISTRY}"