version: '3.8'

services:
  db:
    image: mongo
    ports:
      - '27017:27017'
  bot:
    image: sillock/icelandicdiscordbot:latest
    #configs:
    #  - source: icelandicdiscordbot-config
    #    target: ./src/main/resources/application.properties
    depends_on:
      - db

#configs:
#  icelandicdiscordbot-config:
#    external: true
